name: Update DAppNodePackage

on:
  push:
    tags:
    - '*'

jobs:
  dappnode-update-beacon-chain:
    name: Trigger the beacon-chain DAppNodePackage update
    runs-on: ubuntu-latest
    steps:
    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    - name: Send dispatch event to DAppNodePackage beacon-chain repository
      env: 
        DISPATCH_REPO: dappnode/DAppNodePackage-prysm-beacon-chain
      run: |
        curl -v -X POST -u "${{ secrets.PAT_GITHUB }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" \
        --data '{"event_type":"new_release", "client_payload": { "tag":"${{ steps.get_tag.outputs.TAG }}"}}' \
        https://api.github.com/repos/$DISPATCH_REPO/dispatches
        
  dappnode-update-validator:
    name: Trigger the validator DAppNodePackage update
    runs-on: ubuntu-latest
    steps:
    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    - name: Send dispatch event to DAppNodePackage validator repository
      env: 
        DISPATCH_REPO: dappnode/DAppNodePackage-prysm-validator
      run: |
        curl -v -X POST -u "${{ secrets.PAT_GITHUB }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Content-Type: application/json" \
        --data '{"event_type":"new_release", "client_payload": { "tag":"${{ steps.get_tag.outputs.TAG }}"}}' \
        https://api.github.com/repos/$DISPATCH_REPO/dispatches
